server:
  port: 8080

# 设置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

